config/routes.rb
Rails.application.routes.draw do
 resources :categories
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show,:edit,:destroy, :update]
  def index
    @categories = Category.all
  end
  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to @category
    else
      render 'new'
    end
  end

def edit
  
end
  def update
    if @category.update(category_params)
      redirect_to @category

    else
      render 'edit'

    end
  end

def destroy
  @category.destroy

  redirect_to categories_path
end
  def set_category
    @category = Category.find(params[:id])
  end
  private
  def category_params
    params.require(:category).permit(:name, :price, :description, :code)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<div class="row">
<div class="col-md-3"></div>

<div class="col-md-6">
  <h1>The Category</h1>
<%= simple_form_for @category do |f| %>
 <div class="form-group">
<%= f.label :name %>
<%= f.text_field :name, class: "form-control"%>
</div>
 <div class="form-group">
<%= f.label :price %>
<%= f.text_field :price, as: :integer, class: "form-control"%>
</div>
 <div class="form-group">
<%= f.label :description %>
<%= f.text_field :description, class: "form-control"%>
</div>
 <div class="form-group">
<%= f.label :code %>
<%= f.text_field :code, class: "form-control"%>
</div>

<%= f.button :submit, class: "btn btn-primary"%>
<% end %>
</div>

<div class="col-md-3"></div>
</div>

app/views/categories/edit.html.erb
<%= render 'form'%>
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<div class="container">
  <h1>Listing categories</h1>
  <table class="table .table-striped .table-hover">
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th>Description</th>
      <th>Code</th>
      <th colspan="3">Action</th>
    </tr>

    <% @categories.each do |c| %>
    <tr>
      <td><%= c.name %></td>
      <td><%= c.price %></td>
      <td><%= c.description %></td>
      <td><%= c.code %></td>
      <td><%= link_to 'Show', category_path(c) %> / 
        <%= link_to 'Edit', edit_category_path(c) %> / 
        <%= link_to 'Destroy', category_path(c), 
        method: :delete,
        data: { confirm: 'Are you sure?' } %></td>
      </tr>
      <% end %>
    </table>

app/views/categories/new.html.erb
<%= render 'form'%>

app/views/categories/show.html.erb
<div class="container">
  <div class="well">
    <h3>Hello ^^ Nice day</h3>
    <p>
      <strong>Name:</strong>
      <%= @category.name %>
    </p>

    <p>
      <strong>Price:</strong>
      <%= @category.price %>
    </p>
    <p>
      <strong>Description:</strong>
      <%= @category.description %>
    </p>

    <p>
      <strong>Code:</strong>
      <%= @category.code %>
    </p>

    <%= link_to 'Back', categories_path %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CRUDTest</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>